#+ summary: "Retrieve the nitrogen dioxide concentration (mcg/m3) per month in captitals of EU countries for a specific NUTS country code (e.g., PL, LT, NO, or * for all) and/or for specific date (format: yyyy-mm) <=2024-04 (* for all)"
#+ description: "NOTE: make sure response content type is application/json"
#+ endpoint: "https://www.foodie-cloud.org/sparql"
#+ tags: [ "json" ]
#+ method: "GET"
#+ defaults:
#+   - nutsCode: "PL"
#+   - date: "2024-04"
#+ endpoint_in_url: False
#+ transform: {
#+   "nuts2": "?nuts2",
#+   "date": "?date",
#+   "recyclingRate": "?obsValue",
#+ }


PREFIX  qb:   <http://purl.org/linked-data/cube#>
PREFIX  sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX  e:    <http://ontologycentral.com/2009/01/eurostat/ns#>
PREFIX  g:    <http://eurostat.linked-statistics.org/ontologies/geographic.rdf#>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dataset: <http://eurostat.linked-statistics.org/data/>
PREFIX nuts: <http://nuts.geovocab.org/>
PREFIX spatial: <http://geovocab.org/spatial#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX property: <http://eurostat.linked-statistics.org/property#>
PREFIX ramon: <http://rdfdata.eionet.europa.eu/ramon/ontology/>

SELECT ?nuts2 ?date ?obsValue #(SUM(?pop) AS ?population)
FROM dataset:estat_env_air_no2.ttl
FROM nuts:
WHERE
{ 
?observation  qb:dataSet        dataset:estat_env_air_no2 ;
               property:freq                    ?freq ;
               property:airpol           ?airpol ;
               property:unit		       ?unit ;
               property:geo                     ?ugeo ; # variable
               property:TIME_PERIOD        ?period ; # variable 
               sdmx-measure:obsValue     ?obsValue .
  BIND (IF (CONTAINS(STR(?ugeo), "_CAP"),STRBEFORE(STRAFTER(STR(?ugeo),"http://eurostat.linked-statistics.org/dic/geo#"),"_CAP"),STRBEFORE(STRAFTER(STR(?ugeo),"http://eurostat.linked-statistics.org/dic/geo#"),"_V")) as ?code)
  #BIND (STRBEFORE(STRAFTER(STR(?ugeo),"http://eurostat.linked-statistics.org/dic/geo#"),"_CAP") as ?code)
  BIND(IRI(CONCAT ("http://nuts.geovocab.org/id/",?code)) as ?nuts2) .
  FILTER (?_nutsCode = "*" || ?code = ?_nutsCode)    
  optional {?_nutsCode ?p ?o}
  BIND (STRAFTER(STR(?period),"http://eurostat.linked-statistics.org/dic/TIME_PERIOD#") as ?date)  
  FILTER (?_date = "*" || ?date = ?_date)    
  optional {?_date ?p1 ?o1}
}
#GROUP BY ?nuts2
ORDER BY ?nuts2



